export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const MEMBERSHIP_REGISTRATION_SUCCESS = "MEMBERSHIP_REGISTRATION_SUCCESS";
export const MEMBERSHIP_REGISTRATION_FAIL = "MEMBERSHIP_REGISTRATION_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const GET_MEMBERSHIP_PLANS_SUCCESS = "GET_MEMBERSHIP_PLANS_SUCCESS";
export const GET_MEMBERSHIP_PLANS_ERROR = "GET_MEMBERSHIP_PLANS_ERROR";
export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";
export const GET_ALL_USERS_FAILURE = "GET_ALL_USERS_FAILURE";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_ERROR = "GET_TRANSACTIONS_ERROR";
export const INITIALIZE_TRANSACTION_SUCCESS = "INITIALIZE_TRANSACTION_SUCCESS";
export const INITIALIZE_TRANSACTION_FAILURE = "INITIALIZE_TRANSACTION_FAILURE";
export const LOAD_CONTRACT = "LOAD_CONTRACT";
export const GET_TOKEN_DETAILS = "GET_TOKEN_DETAILS";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SET_LOADING = "SET_LOADING";

export const CONNECT_WALLET = "CONNECT_WALLET";
export const CONNECT_GUEST = "CONNECT_GUEST";
export const DISCONNECT_WALLET = "DISCONNECT_WALLET";
export const MONITOR_ACCOUNT_CHANGED = "MONITOR_ACCOUNT_CHANGED";
export const MONITOR_DISCONNECT = "MONITOR_DISCONNECT";
