export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const MEMBERSHIP_REGISTRATION_SUCCESS = "MEMBERSHIP_REGISTRATION_SUCCESS";
export const MEMBERSHIP_REGISTRATION_FAIL = "MEMBERSHIP_REGISTRATION_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const CLEAR_MESSAGES = "CLEAR_MESSAGES";
export const GET_MEMBERSHIP_PLANS_SUCCESS = "GET_MEMBERSHIP_PLANS_SUCCESS";
export const GET_MEMBERSHIP_PLANS_ERROR = "GET_MEMBERSHIP_PLANS_ERROR";
export const GET_TRANSACTIONS_SUCCESS = "GET_TRANSACTIONS_SUCCESS";
export const GET_TRANSACTIONS_ERROR = "GET_TRANSACTIONS_ERROR";
export const INITIALIZE_TRANSACTION_SUCCESS = "INITIALIZE_TRANSACTION_SUCCESS";
export const INITIALIZE_TRANSACTION_FAILURE = "INITIALIZE_TRANSACTION_FAILURE";

export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

export const SET_LOADING = "SET_LOADING";
